[install]
is_configured = 0

[ui]
is_visible = 1
label = Frothly BOTS Hunts

[launcher]
author = Jacob Hess
description = Threat-hunting dashboards and detections for Splunk Boss of the SOC v3.
version = 0.2.0
