[frothly_aws_cloudtrail]
search = sourcetype=aws:cloudtrail

[frothly_o365_management]
search = sourcetype=ms:o365:management

[frothly_aad_signin]
search = sourcetype=ms:aad:signin

[frothly_wineventlog_security]
search = sourcetype=WinEventLog:Security

[frothly_sysmon]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational"

[frothly_stream_dns]
search = sourcetype=stream:dns
