[frothly_index]
definition = index=botsv3
iseval = 0

[rfc1918(1)]
args = ip
definition = cidrmatch("10.0.0.0/8",$ip$) OR cidrmatch("172.16.0.0/12",$ip$) OR cidrmatch("192.168.0.0/16",$ip$)
iseval = 0

[cryptomining_pools]
definition = (query="*coinhive.com" OR query="*minexmr.com")
iseval = 0

[frothly_users]
definition = UserId="*@froth.ly"
iseval = 0
