[eventtype=frothly_aws_cloudtrail]
change = enabled
cloud = enabled

[eventtype=frothly_o365_management]
change = enabled
cloud = enabled

[eventtype=frothly_aad_signin]
authentication = enabled
cloud = enabled

[eventtype=frothly_wineventlog_security]
authentication = enabled
endpoint = enabled

[eventtype=frothly_sysmon]
endpoint = enabled
process = enabled

[eventtype=frothly_stream_dns]
network = enabled
resolution = enabled
dns = enabled
